#!/bin/bash
 
# Установка переменных для репозитория
REPO_URL="https://github.com/Evgenii-379/shvirtd-example-python"
TARGET_DIR="/opt/docker_practice"
 
# Обновление и установка необходимых пакетов
sudo apt update
sudo apt install -y git
 
# Клонирование форк-репозитория в каталог /opt
sudo git clone "$REPO_URL" "$TARGET_DIR"
 
# Переход в каталог проекта
cd "$TARGET_DIR" || exit
 
# Запуск проекта с помощью Docker Compose
sudo docker compose up -d
